Vagrant.configure(2) do |config|
  config.vm.box = "ubuntu/xenial64"

  config.vm.hostname = 'tomcat' #set vm name to tomcat
  config.vm.synced_folder "workdata/", "/workdata"

  config.vm.provider 'virtualbox' do |virtualbox|
    virtualbox.linked_clone = true
    virtualbox.name = 'tomcat'
    virtualbox.memory =  1024
    virtualbox.cpus = 1
    virtualbox.gui = false #changed to false for headless start (without GUI)
    virtualbox.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
    virtualbox.customize ["modifyvm", :id, "--natdnsproxy1", "on"]
  end

  config.vm.network "forwarded_port", guest: 8080, host: 8080, protocol: "tcp"
  config.vm.network "forwarded_port", guest: 9090, host: 9090, protocol: "tcp"

  config.vm.provision "shell", path: "user-data-scripts/user-data.sh"
  config.vm.provision "shell", path: "machine-content/port-modifier.sh"

end